apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: definition-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - definition.k8s.util.xyz
      secretName: definition-app-tls
  rules:
    - host: definition.k8s.util.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: definition-app
                port:
                  number: 80