---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  labels:
    app: postgres-cm
data:
  # This is NOT a good way to store/reference passwords, but since it's restricted to the cluster
  # and nothing private is stored just definitions, not much is gained by making it private
  POSTGRES_DB: "dictionary"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_URL: "postgres://postgres:postgres@postgres-lb-service.default.svc.cluster.local:5432/dictionary"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: linode-block-storage-retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres-statefulset
spec:
  replicas: 1
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgres-statefulset
  template:
    metadata:
      labels:
        app: postgres-statefulset
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - name: postgres-port
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-cm
          volumeMounts:
            - name: postgres-db-vol
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
         - name: postgres-db-vol
           persistentVolumeClaim:
              claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb-service
  labels:
    app: postgres-lb-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres-port
  selector:
    app: postgres-statefulset
---
